POST http://localhost:3000/api/users/create HTTP/1.1
content-type: application/json

{
  "name": "Felippe Santana",
  "email": "felippefsantana02@gmail.com",
  "password": "pass@123"
}

### Users - find all users

GET http://localhost:3000/api/users/ HTTP/1.1

###  Users - find user

GET http://localhost:3000/api/users/732c42d5-2967-498d-8107-57c31833fbaa HTTP/1.1

### Users - update user

PATCH http://localhost:3000/api/users/update/732c42d5-2967-498d-8107-57c31833fbaa HTTP/1.1
content-type: application/json

{
  "name": "Felippe Santana",
  "email": "felippefsantana02@gmail.com"
}

### Users - delete user

DELETE http://localhost:3000/api/users/delete/044e3d9c-f154-449a-9244-3cde10ef45df HTTP/1.1

### Authentication - login

POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "felippefsantana02@gmail.com",
  "password": "pass@123"
}

### Chats - create new chat

POST http://localhost:3000/api/chats/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxN2ZkNTMwLWRiZWItNGQwYi04Mjg2LWY0NWY5YWU2OTFjNSIsImVtYWlsIjoiZmVsaXBwZWZzYW50YW5hMDJAZ21haWwuY29tIiwiaWF0IjoxNzMxMzQxNTI2LCJleHAiOjE3MzE0Mjc5MjZ9.-70xE6x11AUqCYiaCOWSNMlC-tR0PRJ5T-U-Xe51DEw

{
  "name": "",
  "slug": "",
  "members": [
    "7f81de9f-3d33-409e-a174-5d183e6d885f"
  ]
}

### Chats - find chat

GET http://localhost:3000/api/chats/07bfce56-17a1-429b-9059-49728a4e4401 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxN2ZkNTMwLWRiZWItNGQwYi04Mjg2LWY0NWY5YWU2OTFjNSIsImVtYWlsIjoiZmVsaXBwZWZzYW50YW5hMDJAZ21haWwuY29tIiwiaWF0IjoxNzMxMzQxNTI2LCJleHAiOjE3MzE0Mjc5MjZ9.-70xE6x11AUqCYiaCOWSNMlC-tR0PRJ5T-U-Xe51DEw

### Chats - find user chats

GET http://localhost:3000/api/chats HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxN2ZkNTMwLWRiZWItNGQwYi04Mjg2LWY0NWY5YWU2OTFjNSIsImVtYWlsIjoiZmVsaXBwZWZzYW50YW5hMDJAZ21haWwuY29tIiwiaWF0IjoxNzMxMzQxNTI2LCJleHAiOjE3MzE0Mjc5MjZ9.-70xE6x11AUqCYiaCOWSNMlC-tR0PRJ5T-U-Xe51DEw

### Messages - create message
POST http://localhost:3000/api/messages/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxN2ZkNTMwLWRiZWItNGQwYi04Mjg2LWY0NWY5YWU2OTFjNSIsImVtYWlsIjoiZmVsaXBwZWZzYW50YW5hMDJAZ21haWwuY29tIiwiaWF0IjoxNzMxMzQxNTI2LCJleHAiOjE3MzE0Mjc5MjZ9.-70xE6x11AUqCYiaCOWSNMlC-tR0PRJ5T-U-Xe51DEw

{
  "chatId": "df224e9f-0a13-4dde-94d7-ed56c49cdd51",
  "content": "teste 123"
}
